# k8s-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: campa-deployment
  labels:
    app: campa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: campa
  template:
    metadata:
      labels:
        app: campa
    spec:
      containers:
      - name: campa-container
        image: gowdavidwanhm/campa:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: campa-service
spec:
  selector:
    app: campa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort
